import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run cf-typegen` from wrangler.jsonc — not ours to lint.
    "worker-configuration.d.ts",
    // Build output: the adapter's bundle, and the one wrangler dev writes under
    // .wrangler/tmp/. Both are bundled third-party code and both fail our rules.
    ".open-next/**",
    ".wrangler/**",
  ]),
]);

export default eslintConfig;
