/**
 * `.open-next/worker.js` is generated by `opennextjs-cloudflare build`, so it exists after a
 * build and not before. Importing it directly made `tsc` non-deterministic: with the file
 * present the import resolved and a `@ts-expect-error` above it became "unused", which is
 * itself an error; without it, the import failed. Declaring the module pins the type in both
 * states, and `.open-next` is excluded in tsconfig so the generated bundle is never
 * type-checked as source.
 */
declare module "*/.open-next/worker.js" {
  // Spelled out rather than `ExportedHandler<CloudflareEnv>`, whose `fetch` is optional —
  // which would make `handler.fetch(...)` "possibly undefined" at the call site. The
  // generated worker always exports it.
  const handler: {
    fetch(
      request: Request,
      env: CloudflareEnv,
      ctx: ExecutionContext,
    ): Response | Promise<Response>;
  };
  export default handler;
}
